### ISSUE TITLE
version mismatch error after debug built

### ISSUE THREAD

**Issue by aguskov1987** [fcanas/node-native-boilerplate#15]
I compiled a debug version of node. After I ran the following commands:
node-gyp configure --debug --nodedir="path-to-node"
node-gyp build --debug --nodedir="path-to-node"

The project successfully compiled. However, when I try to require the new module, the following error is generated:

> var n = require('./')
Error: Module version mismatch. Expected 48, got 52.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\AndreyG\Documents\Stuff\node-native-boilerplate\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\AndreyG\Documents\Stuff\node-native-boilerplate\index.js:1:104)
    at Module._compile (module.js:570:32)

I've tried both the global node and the debug node.exe versions

**Comment by aguskov1987** [comment]
I was incorrectly starting the debug version of node.exe. Solved by going into the debug folder of the node build and starting (double-clicking) the node.exe
